train_file: '/home/wenrui/Projects/MIMIC/Data/SIIM-ACR/archive/train.csv'
valid_file: '/home/wenrui/Projects/MIMIC/Data/SIIM-ACR/archive/test.csv'
test_file: '/home/wenrui/Projects/MIMIC/Data/SIIM-ACR/archive/test.csv'

image_res: 224
batch_size: 64
test_batch_size: 64
num_classes: 1
temp: 0.07
mlm_probability: 0.15
queue_size: 8192
momentum: 0.995
alpha: 0.4

optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-5, epochs: 100, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 20, cooldown_epochs: 0}
