train_file: "SIIM-CLS/siim-acr-pneumothorax/stage_1_train_images.csv"
valid_file: "SIIM-CLS/siim-acr-pneumothorax/stage_1_test_images.csv"
test_file: "SIIM-CLS/siim-acr-pneumothorax/stage_1_test_images.csv"

image_res: 224
batch_size: 64
test_batch_size: 64
num_classes: 1
temp: 0.07
mlm_probability: 0.15
queue_size: 8192
momentum: 0.995
alpha: 0.4
percentage: 1.0

optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-5, epochs: 200, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 20, cooldown_epochs: 0}
