# test_file: '/home/wenrui/Projects/MIMIC/MedKLIP/setting/rsna_test.csv'
test_file: '/home/wenrui/Projects/MIMIC/MedKLIP/Sample_Zero-Shot_Grounding_RSNA/data_sample/test.csv'
disease_book: '/home/wenrui/Projects/MIMIC/MedKLIP/Sample_Zero-Shot_Grounding_RSNA/observation explanation.json'
# anatomy_book: '/home/wenrui/Projects/MIMIC/MedKLIP/Sample_Zero-Shot_Grounding_RSNA/position description.json'

image_res: 224
test_batch_size: 64

d_model: 256
res_base_model: 'resnet50'
num_queries: 75
dropout: 0.1
attribute_set_size: 2
N: 4
H: 4
text_encoder: 'emilyalsentzer/Bio_ClinicalBERT'
